site_name: form gather
nav:
  - Home: index.md
  - User Guide:
    - Admin Panel: adminPanel.md
    - Radio Button: radio_button.md
    - Text Input: text_input.md
    - Select Dropdown: select_dropdown.md
  - Export: export.md
theme: material
